### ISSUE TITLE
test_all.pl fails on "4. Checking that aTRAM works correctly..."

### ISSUE THREAD

**Issue by sanjuroj** [juliema/aTRAM#161]
I ran the configure.pl script and got this message when I asked to test the aTRAM functionality:

```
Something went wrong in testing...run "aTRAM/test/test_all.pl debug" and examine the results of debug.log.
```

This tail end of the logfile when I run test_all.pl debug is copied below and I don't know how to interpret the results.  When I just run aTRAM.pl, I get the usage message, so it's functioning to some extent.

```
150819 16:17:30:                writing out 2_len_763_cov_5.4
150819 16:17:30:                writing out reverse-complement of 1_len_2946_cov_6.4


Contigs by target coverage:
contig  aTRAM_target_start      testref aTRAM_target_end        total score
1.4_len_1958_cov_5.0    -       374     76.2    450.2
1.6_len_758_cov_4.2     -       182     -       182
2.2_len_2123_cov_5.7    -       374     76.2    450.2
2.6_len_763_cov_5.2     -       182     -       182
3.4_len_763_cov_5.3     -       182     -       182
3.1_len_2346_cov_5.8    -       374     76.2    450.2
4.1_len_2701_cov_5.7    -       374     76.2    450.2
4.3_len_763_cov_5.4     -       182     -       182
5.2_len_763_cov_5.4     -       182     -       182
5.1_len_2946_cov_6.4    -       374     76.2    450.2
150819 16:17:30: Returning 0 from <...>/programs/aTRAM/test/../aTRAM.pl
```

**Comment by juliema** [comment]
Hey Sanjuro,

Did you build the atram library before running aTRAM.pl?

**Comment by sanjuroj** [comment]
Hi Julie, 

No, I didn't realize I had to do that.  What is the appropriate linux command line to build the library?

**Comment by juliema** [comment]
Ahh yeah sure. Ok so the first step is to build the library. You want your
reads in fasta or fastq format.

per format_sra.pl -1input read1.fastq -2input read2.fastq -out databasename

This can take like an hour or so depending on how big your library is.

Then you can assemble your loci from that library with aTRAM.pl

Thanks!

**Comment by sanjuroj** [comment]
Ah, ok, so just just to be clear, the test_all.pl script isn't run on a set of test data that you provide, it's designed to be run on our own data, once we've built the library.  Thanks!

**Comment by daisieh** [comment]
(actually no, the test script builds its own test library and runs on that. I'm not sure what happened here.)

**Comment by juliema** [comment]
yeah I am not sure why it failed in the test_all.pl stage, we would have to
dig further, however, my experience is that most of the time it fails on
the extra pipelines that are not well used at this point (e.g. the
alignment pipeline) and because it was able to assemble contigs I suspect
aTRAM itself will work fine.

**Comment by sanjuroj** [comment]
I'm installing it for someone else and I've told them to try running it with their data, so hopefully it will run without issues.  If not, we'll let you know :-)

**Comment by juliema** [comment]
We are doing a full rewrite of aTRAM and are going to handle this at that time. Currently the test_all.pl function looks to use velvet as the assembler in the test, we will be allowing the test function to use the installed assembler in this process in the future.

**Comment by juliema** [comment]
going to close this issue as we port to 2.0. If this issue still persists please create a new issue.
