### ISSUE TITLE
Running aTRAM with AbySS

### ISSUE THREAD

**Issue by erdikucuk** [juliema/aTRAM#163]
Hi,
I would like to run aTRAM with AbySS 1.5.2. When I  check with configure.pl, it says abyss-pe is ready to use but in the actual run aTRAM complains because it couldn't find a file called "abyss-pe.pm"  in the assembler dir. I am not sure what is meant by that. Is abyss-pe.pm something I should create?
Cheers,
Erdi

**Comment by juliema** [comment]
Hi Erdi,

Actually I know what is going on.  Let me push a quick change up the repo
and that should fix that and one other issue I have found lately running
aTRAM with abyss.

more soon.

Julie

**Comment by juliema** [comment]
actually I think that there might be another issue.

When you are running aTRAM  when you put int he assembler  did you write
Abyss or Abyss-pe?  If you wrote Abyss-pe that would explain the problem.
Try running it with Abyss.

Let me know if that works.

J

**Comment by erdikucuk** [comment]
Hi Julie,
It seems like running with Abyss (instead of abyss-pe) is working. Thanks a lot for your help!
Cheers,
Erdi

**Comment by juliema** [comment]
Yess! Excellent!
