### ISSUE TITLE
Doesn't like folders with spaces

### ISSUE THREAD

**Issue by etwatson** [juliema/aTRAM#166]
I know. Who does that? I'm borrowing a machine and aTRAM doesn't like spaces in the folder names. FYI.

**Comment by juliema** [comment]
Thanks for the info Eric. Yeah that can be rather frustrating.  Will keep
this in mind for the next version.

J

**Comment by rafelafrance** [comment]
Version 2 allows you to put single quotes around the file/dir names like so

--output 'my output file.fasta'.
