### ISSUE TITLE
file2_fastq

### ISSUE THREAD

**Issue by jorgeoyhe** [juliema/aTRAM#167]
Sorry to bother you, I'm new on your software
I had an error when running a fasta file to make the aTRAM database so I run it for 2 fastq files (SRR2007618_1.fastq and SRR2007618_2.fastq from the SRX1017350 project). 
This run with both files showed me errors in SRR2007618_2.fastq file and gave me several files a library for the SRR2007618_1.fastq but the SRR2007618_2.fastq 
The error are like:
......./SRR2007618_2.fastq: line 1: @SRR2007618.1: command not found
......./SRR2007618_2.fastq: line 2: AGACGAGGAAAAATTTATGATTACATTTAATAAGGTCATGAGTGATTCAAAATATCAGGATATAGAACGCGCTGAGAACG: command not found
......./SRR2007618_2.fastq: line 3: +: command not found
......./SRR2007618_2.fastq: line 4: HHHJJIJJIJJJJJJJJGJIJGIJJJJJJIJIHEHDGIJJHJHHHJJJJJIJJJJJJIHHEHJIHHHHHFDDDDDDDDDD: command not found
......./SRR2007618_2.fastq: line 5: @SRR2007618.2: command not found
......./SRR2007618_2.fastq: line 6: TGTTGATTTTTTGCGTTTATGTTCTTGTTGCAATTGGTTTTGTTGTCGTTCTTGTTCTCTTTGTTGTCGTTCTTGTTCTC: command not found
.............. untill lane 76

When I run only SRR2007618_1.fastq I have a full library with a final message  "......... added 1995753 sequences in 68.5093 seconds.

the command I use is 
perl format_sra.pl -input /.../SRR2007618_1.fastq|/../SRR2007618_2.fastq -out /.../my_library

Can you help me?

**Comment by daisieh** [comment]
You have a pipe character `|` in between the two file names in your command, so the command line thinks that you're trying to execute the first word after the pipe as a command. Use a space instead.

**Comment by jorgeoyhe** [comment]
Thank you very much Daisie
It was that
