### ISSUE TITLE
Error code with assembly using Trinity

### ISSUE THREAD

**Issue by etvedte** [juliema/aTRAM#177]
I've successfully installed aTRAM on my computer as well as all the BLAST dependencies. I've also successfully installed velvet and ran test datasets using commands with the command -assembler Velvet. I tried installing Trinity on my computer to see how the assemblies of the two programs compare for test data. I tried installing both the newest version of Trinity (2.4.0) and the latest version it seems aTRAM was configured for (I saw a folder with Trinity 2.2.0 info). When I run aTRAM.pl it says that the command /Usr/bin/Trinity exited with 2. Also of note, I needed to rename the Trinity executable from "Trinity" to "Trinity.pl" in order for the configuration command to recognize the appropriate file.

Any thoughts of why I can't get aTRAM to run with Trinity?

**Comment by juliema** [comment]
Hi, great you are using atram. We have upgraded atram to work with  trinity version 2.2.0. we just tagged a new release with this version today. Will you try with the newest release of aTRAM with Trinity 2.2.0?.

**Comment by juliema** [comment]
going to close this issue as we port to 2.0. If this issue still persists please create a new issue.
