### ISSUE TITLE
All contigs file

### ISSUE THREAD

**Issue by ryanafolk** [juliema/aTRAM#193]
Can you name the current final output with this suffix: .filtered_contigs.fa

And then create a file with ALL assembled contigs from ALL iterations where each contig indicates what iteration it came from and the file has this suffix: .all_contigs.fa

**Comment by juliema** [comment]
Currently it seems that the 'all_contigs' file and the 'filtered_contigs' file have the exact same reads in them. I think they are the filtered reads.



atram2.abyss.uce-1511.fasta.all_contigs.fasta
atram2.abyss.uce-1511.fasta.filtered_contigs.fasta
