### ISSUE TITLE
potential issue in abyss - longseqdist step

### ISSUE THREAD

**Issue by juliema** [juliema/aTRAM#194]
on some loci gets stuck on this step for days. -- 
taxa: H108 locus 225 - Folk data 
on moose ryanfolk_atram_2_assemblies

**Comment by ryanafolk** [comment]
It specifically gets stuck in abyss' subprocess executable called abyss-longseqdist. Could be a long-reads issue, although we checked the longreads file in the tmp directory and it looks like a legal fasta sequence.

**Comment by rafelafrance** [comment]
Can we confirm that this is still an issue?
