### ISSUE TITLE
turn off filtering option only one iteration

### ISSUE THREAD

**Issue by juliema** [juliema/aTRAM#195]
Can we have a flag the user can set that will only allow a single iteration and outputs all of the assemblies. -- without filtering them -- no re-blasting. 

process - blast - assemble - quit.

**Comment by rafelafrance** [comment]
Does setting the iteration count to 1 work for this?

**Comment by juliema** [comment]
Maybe we dont need to have it do a single iteration but just does not do the filtering and uses the non-filtered in the next iteration?

**Comment by juliema** [comment]
in atram1 if there were no contigs that passed the filtering step the whole
run would fail and nothing would be printed out, so I am not sure what
would happen in that circumstance.

We have some insect genomes with tiny tiny exons and because they are so
small nothing passes the filtering step. It is a particular feature of
these genomes so in this case we just want all the assembled contigs.

**Comment by rafelafrance** [comment]
When there are no contigs atram will stop but you will get a message telling you why and the output will contain all of the data from the other iterations.

**Comment by juliema** [comment]
ok this still outputs a filtered_contigs file. remove that and I think we have it.
