### ISSUE TITLE
spades assembler

### ISSUE THREAD

**Issue by juliema** [juliema/aTRAM#199]
Add in one more assembler. R-folk will add in how to run it and put executables on moose for testing.

**Comment by ryanafolk** [comment]
Example run:

spades.py --only-assembler --threads 1 --cov-cutoff 8 -1 lib_I9.01.paired_end_1.fasta -2 lib_I9.01.paired_end_2.fasta -o spades

Then you go into the -o directory, "spades" or whatever you call it, and fetch contigs.fasta. That's your result. This assembler has very few options, so this should be sufficient. 

Notice that the kmer argument goes unused. Spades tries to guess the best kmer.

**Comment by ryanafolk** [comment]
The source is hard to make on both workstations, so I copied 3.10.1 binaries from Hipergator. They are in usr/local/bin
