### ISSUE TITLE
Error when trying to split FASTA queries

### ISSUE THREAD

**Issue by Andy-B-123** [juliema/aTRAM#214]
Hi, I have been able to run aTRAM using a single query file (using '-q single_Query) without any problems. However when I attempt to run multiple sequences in a single FASTA file using the '-Q' parameter I receive the following error:

> Traceback (most recent call last):
>   File "/flush1/bac050/aTRAM/aTRAM/atram.py", line 533, in <module>
>     assemble(ARGS)
>   File "/flush1/bac050/aTRAM/aTRAM/atram.py", line 26, in assemble
>     queries = split_queries(args)
>   File "/flush1/bac050/aTRAM/aTRAM/atram.py", line 94, in split_queries
>     queries = args['query'][:]
> TypeError: 'NoneType' object is not subscriptable

I am running the following command: 

`python /flush1/bac050/aTRAM/aTRAM/atram.py -b aTLib05 -Q MultiQuery1.fasta -i 5 --cpus 10  --kmer 31 -o MultiQueryOutput --log-file MultiQueryOutput -a trinity --bowtie2`

I do not get the error message when I use a single query FASTA file and use the '-q' parameter. 

I am running aTRAM on a computing cluster and have loaded in Python 3.5.1, Blast+ and Spades.

I haven't seen this issue posted here so I am unsure where that error originates from. Any help is appreciated.

I've attached the FASTA files I am using for the single query and multi query attempts. (Extenstion changed to .txt to allow upload, was originally .fasta)

[MultiQuery.txt](https://github.com/juliema/aTRAM/files/1658458/MultiQuery.txt)
[SingleQuery.txt](https://github.com/juliema/aTRAM/files/1658467/SingleQuery.txt)

**Comment by rafelafrance** [comment]
I just verified with your data to be extra sure, we have fixed this bug in a later release. Try running this with version v2.alpha.5. Let us know if this works for you.

**Comment by Andy-B-123** [comment]
Hi, thank you for the rapid response. Can confirm, running version v2.alpha.5 has fixed the problem. Thank you for your help!
