### ISSUE TITLE
no module named 'numpy'

### ISSUE THREAD

**Issue by adhornsby** [juliema/aTRAM#223]
I'm trying to run atram_preprocessor.py and am getting an error that numpy is missing.  I assumed that the virtual environment would supply all the modules necessary (except the blast and assembly modules).  Do I misunderstand this and need to install numpy independently?  Thanks very much.

> Traceback (most recent call last):
>   File "/aTRAM/atram_preprocessor.py", line 15, in <module>
>     import numpy as np
> ImportError: No module named 'numpy'

**Comment by juliema** [comment]
numpy is one of the modules installed in the requirements.txt file (numpy==1.14.2), so it should be installed.  Quick q. did you get any errors when you installed the packages from requirements.txt?

**Comment by rafelafrance** [comment]
Actually, aTRAM needs python v3 not v2. The virtual environment is only a container for the modules we use. You have to fill that container with the modules via the following command:

`pip install -r requirements`

Have a look at the [readme](https://github.com/juliema/aTRAM). Scroll past the Background section and look at the Installation section for a full set of instructions.

FYI: We are planning on putting atram on PyPI which will simplify this installation but we're still in in alpha.

**Comment by juliema** [comment]
We are using python 3.5 right now in atram so you should not have to switch to an older version o python.  I  just want to check a  few things.  

1. did you set up a virtual environment for your install?

virtualenv venv -p python3
source venv/bin/activate
pip install -r requirements.txt

2. then when you run the program you should be in the virtual environment every time:
source venv/bin/activate

let us know if that helps!

**Comment by adhornsby** [comment]
I activated the virtual environment (venv) using python/3.5.0, and initially kept 3.5.0 for the installation.  When I got the error at installation [Expected version spec in enum34; python_version=="2.7" at ;
 python_version=="2.7"] I switched to 2.7.10 hoping that would fix it, but I got the same error.

Let me know if I should paste or attach anything else... I'm at least getting something right since the environment is activated and installation gets to line 10 of requirements.txt before I get the error.

Many thanks for your help!

**Comment by juliema** [comment]
that error suggests that you are either not in the virtual environment or it was not set up with python3.  Can you tell me if when you set up the virtual environment you wrote python3?  Also at the beginning of your command line does it say (venv)? 

if so will you type 
python --version

and tell me what you get?

**Comment by adhornsby** [comment]
I included python3, and the beginning of my command line says (venv).  I'm
running python 3.5.0.

Does the following output from venv setup point to the problem?  I didn't
think it was an error per se so I didn't mind it.

[user@node aTRAM]$ module load gcc/5.2.0
[user@node aTRAM]$ module load python/3.5.0
[user@node aTRAM]$ virtualenv venv -p python3
Already using interpreter /opt/apps/gcc5_2/python/3.5.0/bin/python3
Using base prefix '/opt/apps/gcc5_2/python/3.5.0'
New python executable in venv/bin/python3
Not overwriting existing python script venv/bin/python (you must use
venv/bin/python3)
Installing setuptools, pip, wheel...done.
[user@node aTRAM]$ source venv/bin/activate
(venv)[user@node aTRAM]$ python --version
Python 3.5.0

**Comment by juliema** [comment]
ok will you do

pip install -r requirements.txt

and paste the output?

**Comment by adhornsby** [comment]
Yep, here is the whole output from that:

(venv)[user@node aTRAM]$ pip install -r requirements.txt
Collecting appdirs==1.4.3 (from -r requirements.txt (line 1))
  Using cached
https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting astroid==1.6.2 (from -r requirements.txt (line 2))
  Using cached
https://files.pythonhosted.org/packages/13/f8/c0cb46cb3873209ebe3e97dafab4936348142b907eec6417534caa2dbc9a/astroid-1.6.2-py2.py3-none-any.whl
Collecting attrs==17.4.0 (from -r requirements.txt (line 3))
  Using cached
https://files.pythonhosted.org/packages/b5/60/4e178c1e790fd60f1229a9b3cb2f8bc2f4cc6ff2c8838054c142c70b5adc/attrs-17.4.0-py2.py3-none-any.whl
Collecting autopep8==1.3.4 (from -r requirements.txt (line 4))
  Using cached
https://files.pythonhosted.org/packages/4b/b1/a9a682067584ef35682240c3815b94f36b87d2f3bc274e12e51cc006c182/autopep8-1.3.4.tar.gz
Collecting biopython==1.70 (from -r requirements.txt (line 5))
  Using cached
https://files.pythonhosted.org/packages/72/04/73a4bb22fed40eed26c7e1a673ab51778c577afc3d5dd6f1256424a62c35/biopython-1.70.tar.gz
Collecting configparser==3.5.0 (from -r requirements.txt (line 6))
  Using cached
https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
Collecting coverage==4.5.1 (from -r requirements.txt (line 7))
  Using cached
https://files.pythonhosted.org/packages/35/fe/e7df7289d717426093c68d156e0fd9117c8f4872b6588e8a8928a0f68424/coverage-4.5.1.tar.gz
Collecting flake8==3.5.0 (from -r requirements.txt (line 8))
  Using cached
https://files.pythonhosted.org/packages/b9/dc/14e9d94c770b8c4ef584e906c7583e74864786a58d47de101f2767d50c0b/flake8-3.5.0-py2.py3-none-any.whl
Collecting future==0.16.0 (from -r requirements.txt (line 9))
  Using cached
https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Collecting hypothesis==3.52.0 (from -r requirements.txt (line 10))
  Using cached
https://files.pythonhosted.org/packages/b3/05/e14027585a3d9d751e5598a797584adb7dfd3aeb4515cc9c341894fc21e0/hypothesis-3.52.0.tar.gz
    Complete output from command python setup.py egg_info:
    /tmp/pip-build-yvuy6nup/hypothesis/setup.py:39: UserWarning: This
version of setuptools is too old to correctly store conditional
dependencies in binary wheels.  For more info, see:
https://hynek.me/articles/conditional-python-dependencies/
      'This version of setuptools is too old to correctly store '
    /opt/apps/gcc5_2/python/3.5.0/lib/python3.5/distutils/dist.py:261:
UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in hypothesis setup command: 'install_requires' must be a string
or list of strings containing valid project/version requirement specifiers;
Expected version spec in enum34; python_version=="2.7" at ;
python_version=="2.7"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-build-yvuy6nup/hypothesis
You are using pip version 7.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by juliema** [comment]
ok will you try:
pip install -U pip --ignore-installed
then:
pip install -r requirements.txt

then paste the output again?

**Comment by adhornsby** [comment]
Here it is, with a couple extra commands to verify pip version.  The pip
version warning after installation is gone now, but I'm still getting the
same error code at the very end.

(venv)[user@node aTRAM]$ pip install -U pip --ignore-installed
Collecting pip
  Downloading
https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl
(1.3MB)
    100% |████████████████████████████████| 1.3MB 362kB/s
Installing collected packages: pip
Successfully installed pip-7.1.2
You are using pip version 7.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(venv)[uer@node aTRAM]$ pip install --upgrade pip
Requirement already up-to-date: pip in ./venv/lib/python3.5/site-packages
(10.0.1)

(venv)[user@node aTRAM]$ pip --version
pip 10.0.1 from /home/ahornsby/aTRAM/venv/lib/python3.5/site-packages/pip
(python 3.5)

(venv)[user@node aTRAM]$ pip install -r requirements.txt
Collecting appdirs==1.4.3 (from -r requirements.txt (line 1))
  Using cached
https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting astroid==1.6.2 (from -r requirements.txt (line 2))
  Using cached
https://files.pythonhosted.org/packages/13/f8/c0cb46cb3873209ebe3e97dafab4936348142b907eec6417534caa2dbc9a/astroid-1.6.2-py2.py3-none-any.whl
Collecting attrs==17.4.0 (from -r requirements.txt (line 3))
  Using cached
https://files.pythonhosted.org/packages/b5/60/4e178c1e790fd60f1229a9b3cb2f8bc2f4cc6ff2c8838054c142c70b5adc/attrs-17.4.0-py2.py3-none-any.whl
Collecting autopep8==1.3.4 (from -r requirements.txt (line 4))
  Using cached
https://files.pythonhosted.org/packages/4b/b1/a9a682067584ef35682240c3815b94f36b87d2f3bc274e12e51cc006c182/autopep8-1.3.4.tar.gz
Collecting biopython==1.70 (from -r requirements.txt (line 5))
  Downloading
https://files.pythonhosted.org/packages/55/59/260381d3c98ffeef7657ad163c7d94bb43599040bd5ca5170599bca40892/biopython-1.70-cp35-cp35m-manylinux1_x86_64.whl
(2.2MB)
    100% |████████████████████████████████| 2.2MB 602kB/s
Collecting configparser==3.5.0 (from -r requirements.txt (line 6))
  Using cached
https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
Collecting coverage==4.5.1 (from -r requirements.txt (line 7))
  Downloading
https://files.pythonhosted.org/packages/2c/c0/8047b7cbbcdbd7d21f8d68126196b7915da892c5af3d1a99dba082d33ec0/coverage-4.5.1-cp35-cp35m-manylinux1_x86_64.whl
(202kB)
    100% |████████████████████████████████| 204kB 3.7MB/s
Collecting flake8==3.5.0 (from -r requirements.txt (line 8))
  Using cached
https://files.pythonhosted.org/packages/b9/dc/14e9d94c770b8c4ef584e906c7583e74864786a58d47de101f2767d50c0b/flake8-3.5.0-py2.py3-none-any.whl
Collecting future==0.16.0 (from -r requirements.txt (line 9))
  Using cached
https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Collecting hypothesis==3.52.0 (from -r requirements.txt (line 10))
  Using cached
https://files.pythonhosted.org/packages/b3/05/e14027585a3d9d751e5598a797584adb7dfd3aeb4515cc9c341894fc21e0/hypothesis-3.52.0.tar.gz
    Complete output from command python setup.py egg_info:
    /tmp/pip-install-w3at0w4j/hypothesis/setup.py:39: UserWarning: This
version of setuptools is too old to correctly store conditional
dependencies in binary wheels.  For more info, see:
https://hynek.me/articles/conditional-python-dependencies/
      'This version of setuptools is too old to correctly store '
    /opt/apps/gcc5_2/python/3.5.0/lib/python3.5/distutils/dist.py:261:
UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in hypothesis setup command: 'install_requires' must be a string
or list of strings containing valid project/version requirement specifiers;
Expected version spec in enum34; python_version=="2.7" at ;
python_version=="2.7"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-install-w3at0w4j/hypothesis/

**Comment by rafelafrance** [comment]
For your case you can remove the line from `requirements.txt` that starts with

`hypothesis==3.52.0`

This module is used to run automated tests for our builds and is not required to run atram itself. I suspect that we have to down grade this module for python 3.5.0

**Comment by adhornsby** [comment]
Thanks, that gets me further!  I deleted hypothesis==3.52.0, and now I'm still hitting a similar error at python-language-server:

(venv)[user@node aTRAM]$ pip install -r requirements2.txt
...
Collecting python-language-server==0.17.0 (from -r requirements2.txt (line 32))
  Downloading https://files.pythonhosted.org/packages/fe/c3/8dd9297e91a8bc759bca50f7462a6b71d11f98bb69022ea375f3450a2ec4/python-language-server-0.17.0.tar.gz (55kB)
    100% |████████████████████████████████| 61kB 4.2MB/s 
    Complete output from command python setup.py egg_info:
    error in python-language-server setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in configparser; python_version<"3.0" at ; python_version<"3.0"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-697vgdc1/python-language-server/

**Comment by rafelafrance** [comment]
You may remove both python-language-server & snowballstemmer they are used exclusively for development work and will have no impact on running atram.

Note to self: We have to clean out requirements.txt.

**Comment by adhornsby** [comment]
Is pyls-isort required?  Same error.

Collecting python-language-server (from pyls-isort==0.1.1->-r requirements2.txt (line 28))
  Downloading https://files.pythonhosted.org/packages/97/4c/b561716780888f8df9ed44b5e2b8b499258c31b7722d96da0002483fcdd2/python-language-server-0.19.0.tar.gz (55kB)
    100% |████████████████████████████████| 61kB 3.3MB/s 
    Complete output from command python setup.py egg_info:
    error in python-language-server setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in configparser; python_version<"3.0" at ; python_version<"3.0"

**Comment by adhornsby** [comment]
Awesome, installation completed and it looks like atram_preprocessor.py ran fine.  
Thanks very much!

**Comment by juliema** [comment]
awesome!  thanks!

**Comment by rafelafrance** [comment]
Sorry about all the issues. We've made changes to atram to try and avoid these problems in the future.

If you have other problems please open another issue.
