### ISSUE TITLE
Problem with test suite

### ISSUE THREAD

**Issue by wjj199516** [juliema/aTRAM#224]
When we attempted to install aTRAM on our server, we installed all dependencies successfully, but got  several  ModuleNotFoundError upon running the test suite. Modules Bio and hypothesis were not found, even though we can load these in a session of python. aTRAM itself seems to execute without problems.

Pasted error below:

(venv) [wujiajin@YiBig aTRAM]$ pytest tests
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /data/wujiajin/aTRAM, inifile:
plugins: openfiles-0.3.0, remotedata-0.2.1, arraydiff-0.2, doctestplus-0.1.3
collected 0 items / 5 errors                                                   

==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_atram.py _____________________
ImportError while importing test module '/data/wujiajin/aTRAM/tests/test_atram.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_atram.py:7: in <module>
    from lib.assemblers.base import BaseAssembler
lib/assemblers/base.py:8: in <module>
    import lib.bio as bio
lib/bio.py:4: in <module>
    from Bio import SeqIO
E   ModuleNotFoundError: No module named 'Bio'
______________ ERROR collecting tests/test_atram_preprocessor.py _______________
ImportError while importing test module '/data/wujiajin/aTRAM/tests/test_atram_preprocessor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_atram_preprocessor.py:9: in <module>
    import atram_preprocessor
atram_preprocessor.py:16: in <module>
    from Bio.SeqIO.QualityIO import FastqGeneralIterator
E   ModuleNotFoundError: No module named 'Bio'
____________________ ERROR collecting tests/lib/test_bio.py ____________________
ImportError while importing test module '/data/wujiajin/aTRAM/tests/lib/test_bio.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/lib/test_bio.py:3: in <module>
    from hypothesis import given
E   ModuleNotFoundError: No module named 'hypothesis'
____________________ ERROR collecting tests/lib/test_log.py ____________________
ImportError while importing test module '/data/wujiajin/aTRAM/tests/lib/test_log.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/lib/test_log.py:4: in <module>
    from hypothesis import given
E   ModuleNotFoundError: No module named 'hypothesis'
______________ ERROR collecting tests/lib/assemblers/test_base.py ______________
ImportError while importing test module '/data/wujiajin/aTRAM/tests/lib/assemblers/test_base.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/lib/assemblers/test_base.py:9: in <module>
    from hypothesis import given, assume
E   ModuleNotFoundError: No module named 'hypothesis'
!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 5 error in 0.48 seconds ============================

**Comment by rafelafrance** [comment]
Due to people having problems installing requirements.txt we split the requirements.txt into two files. One for running atram and one for testing atram. If you get into your atram virtual environment and cd into the atram directory you can run:
```
pip install -r requirements_test.txt
``

This has everything in requirements.txt plus the testing libraries.
