### ISSUE TITLE
add pe-assembler

### ISSUE THREAD

**Issue by juliema** [juliema/aTRAM#231]
“pe-assembler”.  (https://academic.oup.com/bioinformatics/article/27/2/167/284712) it uses an extension based approach and not de bruijn graph.
…

**Comment by rafelafrance** [comment]
May I get some input on what a typical run would look like?

The programs compie but with errors so I don't know if they're working right.

My attempts to run the possibly broken programs with the given sample data:
- hash.exe: seems to work
- err.exe: segfaults
- build.exe: errors out
- scaf.exe: seems to work
- fill.exe: core dump
- pa.Asm: errors out

**Comment by juliema** [comment]
Lets put this on the back burner for now.  will revisit later.
