### ISSUE TITLE
Handle old fastq format

### ISSUE THREAD

**Issue by rafelafrance** [juliema/aTRAM#233]
Old fastq files will sometimes have "@" signs in the quality values line. This is causing a problem with the preprocessor.

**Comment by juliema** [comment]
file located in /srv/gspeedq32/atram_troubleshooting/dataset2_qual_Line
fastq file  and a target file.

**Comment by rafelafrance** [comment]
There are roughly 889 sequences in this test file with the issue. However, as far as I can tell, aTRAM is handling this correctly every time. Would you please give me the exact commands you are using for the preprocessor and atram. That should help me track down the issue.
