### ISSUE TITLE
option to remove temporary directories once job is done?

### ISSUE THREAD

**Issue by juliema** [juliema/aTRAM#235]
could we add an option for atram to remove any temporary directories that were made during the run after the job is completed?

**Comment by robgur** [comment]
+1

**Comment by rafelafrance** [comment]
The current plan to complete this issue is:
- Remove --sqlite-temp-dir option. It will now use the --temp-dir option if there is one.
- Have the --temp-dir option delete the directory when it completes.
- Make a new --debug-dir option that will save the temp dir for debuging purposes.

**Comment by juliema** [comment]
yes this sounds like the best plan to handle a number of issues.

**Comment by juliema** [comment]
also - make sure this deletes the temp files after each locus not after the whole run if using the -Q option.

**Comment by rafelafrance** [comment]
The temp dirs now get deleted when the iteration is done. Because the current iteration relies on data from the previous iteration there is some data that hangs around.

For debugging purposes I added the `--keep-temp-dir` option. This prevents the `--temp-dir` option from deleting files.
