### ISSUE TITLE
if the assembler fails, let the user know the number of blast hits 

### ISSUE THREAD

**Issue by juliema** [juliema/aTRAM#236]
it is hard to tell sometimes why a job fails, sometimes it is due to assembler issues but sometimes it is due to very low coverage. The assemblers do not give informative errors. 

It would be nice if once an assembly fails if atram could add an additional error message that says there were X number of blast hits in the original blast.  That will inform the user if the library is just bad or if it is worth trying different assembler options.

**Comment by rafelafrance** [comment]
I am changing this a little to always show the number of blast hits for every iteration.
