### ISSUE TITLE
atram_stitcher - possible formatting issue 

### ISSUE THREAD

**Issue by juliema** [juliema/aTRAM#255]
with the dataset attached the output gives zero results. i suspect there is some sort of formatting issue happening that we did not anticipate.  

[test_data.zip.txt](https://github.com/juliema/aTRAM/files/3336293/test_data.zip.txt)

**Comment by rafelafrance** [comment]
The problem is that the contig names do not contain either the ref name or the taxon name. So they're all being excluded. This may not be what we want but I think I got this logic from the original stitcher code.
