### ISSUE TITLE
Add a cleaning module?

### ISSUE THREAD

**Issue by rafelafrance** [juliema/aTRAM#259]
You have mentioned the importance of cleaning the sequence data. I'm not sure what these all mean.
- Duplicate removal
- Adapter trim
- Quality trim
- Hard trim
- Sequence length trim
- Other?

Questions:
- Is this possible to do easily?
- Would it be useful to to the community?
- Are there existing utilities that do this effectively and, hence, it's not needed in atram itself? (fastqc)

**Comment by juliema** [comment]
it would be very useful to have a stripped down trimming version in atram. something that incorporates just adaptor trimming and quality trimming of fastq files.   That would enable people to go straight from SRA to locus assembly. Lets chat about this.
