### ISSUE TITLE
assemble by trinity using Single-end fq  

### ISSUE THREAD

**Issue by yuhuang-genomics** [juliema/aTRAM#262]
Hi Julie and Rafe,

I tried  to assemble some short exons from single-end fastq sequences by atram.py -a trinity but always get the following error:
ERROR: The assembler failed with error: Command 'Trinity --seqType fa --max_memory 13G --CPU 6 --output '/tmp/ref.fa_01_jxs16t6l/trinity' --full_cleanup --no_bowtie --left '/tmp/ref.fa_01_jxs16t6l/paired_1.fasta' --right '/tmp/ref.fa_01_jxs16t6l/paired_2.fasta'' returned non-zero exit status 2
It seems that the seqs are treated as pair-end reads automatically.
My scripts:
atram_preprocessor.py -b prefix --single-ends prefix.fastq
atram.py -b prefix -q ref.fa -a trinity -o trinity -i 5 --cpus 6
My single-end fastq files:
@J00107:15:H2W35BBXX:1:1218:29135:18457
ATAGAAGATGTTGTCAAAGAATGGCTGTACCTGCTGGAAAAAGAAGGTGGGTGCGCCGACAGCGAGCTCCCGCAAAACCAGCACCTGTAACACAAGACATG
+
,<AF<FAFKKFKKKKKKFAFAKKKKK<FKKKKKKKKKKAKFFFFKFKKKKFFF<AF(A77F<AFAFKKKKFKK,,,<<FKKKKKKKKKFFKKKKFAFK7<K
@J00107:15:H2W35BBXX:1:2122:4826:40134
ATGGCCTGTTTGGAGTCCCACACCGCATAGAAGATGTTGTCAAAGAATGGCTGTACCTGCTGGAAAAAGAAGGTGGGTGCGCTGACAGCGAGCTCCCGCAA
+
AFFFFKFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKAKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
@J00107:15:H2W35BBXX:1:2106:23391:49047
GTTTGGAGTCCCACACCGCATAGAAGATGTTGTCAAAGAATGGCTGTACCTGCTGGAAAAAGAAGGTGGGTGCGCTGACAACGAGCTCCCGCAAAACCAGC
+
A,FFFAKKK<KFKKKK<7FKAFKFFKKKK7FKFKKKKKKKF,A<,,FF<,,AF7FKKKAFKKKKKFKKA7F7<AAFFFAK7FFKAA,A7,A<AFAKA7FFF

Thanks for your help.

Best,
Yu

**Comment by juliema** [comment]
yep this seems like we just need a fix on how atram is calling trinity when there are single--end reads. Rafe will you take a look at this one tomorrow as well?

**Comment by rafelafrance** [comment]
The fix involves some changes to the database, so unfortunately, you will need to run atram_preprocessor.py again to pick up the database changes.

**Comment by yuhuang-genomics** [comment]
Thanks Rafe, unfortunately, I still get the same error with the new script after re-running the atram_preprocessor.py. Trinity command still shows the "--left paired_1.fasta and --right paired_2.fasta". However, I tried velvet and it works, the log file shows that both "-shortPaired" and "-short" reads were used although I only have single-end reads.

**Comment by rafelafrance** [comment]
1. Did you do a `git pull` before you reran the pre-processor?
```bash
cd my/atram/directory
git pull
./atram_prepressor.py ... The same arguments from before
./atram.py ... The same arguments
```
1. If you did, then would it be possible to get a larger subset of your input sequences? Maybe, my theory of what went wrong is itself wrong.

FYI:
1. Trinity seems to be the only assembler that has this problem in aTRAM. IT should work with the other assemblers.
1. My theory of what went wrong is that there are some duplicate names in the input sequences. For instance, if there are some paired-end 1 and end 2 sequences named like`>seq_name:123/1` and `>seq_name_123/2` in the input fastq file then aTRAM (Trinity only) would look at them and say. You've got paired-ends and always run through the paired-end only logic. This is what I was trying to fix.
1. My patch did this:
    1. If you say --single-ends in the pre-processor then atram saves this in the DB and it also changes the names to not use pair-ends in the names.
    1. When running the Trinity it looks for the --single-ends flag and forces atram to go thru the single-ends logic.
    1. I tested that this worked by using two paired-ends files as single ends. The patch worked in the case but as I said above it is possible that something else is going on with your data.
1. Trinity is the only assembler currently used by atram that does not allow you to mix --single-ends with -end-1 and --end-2 (or --mixed-ends).

**Comment by yuhuang-genomics** [comment]
Thanks Rafe. Problem solved! It's the problem of my own fastq, which contains duplicate read names. Thanks for pointing it out. After renaming the headers, aTram works well with Trinity. Thanks for your kind help.

Cheers,
Yu

**Comment by yuhuang-genomics** [comment]
Dear Rafe,

Hmmmm…. Interesting. --single-ends really works now. However, with the new scripts, --mix-ends (mixed with fq_1, fq_2 paired-ends, generated from a bam) which worked well previously does not work any more. Seems like they were treated as single-ends.

**My command：**
atram_preprocessor.py -b prefix --mix-ends prefix.fastq
atram.py -b prefix -q ref.fa -a trinity -o trinity -i 5 --cpus 6

**Sqlite.db:**
SQLite format 3
indexsequences_indexsequences
usCREATE INDEX sequences_index ON sequences (seq_name, seq_end)
_tablesequencessequences
CREATE TABLE sequences (
            seq_name TEXT,
            seq_end  TEXT,
            seq      TEXT)d
tablemetadatametadata
CREATE TABLE metadata (
            label TEXT,
            value TEXT)
single_ends0
version2.2


**Log file:**
2019-09-10 03:52:47 DEBUG: Trinity --seqType fa --max_memory 13G --CPU 6 --output '/tmp/atram_xpc10ieb/Acheilognathidae_Acheilognathus_tonkinensis_ST_Acheilognathidae_Acheilognathus_tonkinensis_ST.E0027.fq.initial.combined.fa_01_x90wmut1/trinity' --full_cleanup --no_bowtie
2019-09-10 03:52:47 DEBUG: Must specify basic parameters:  ex. Trinity --seqType fq --single reads.fq --max_memory 10G  at /zfssz5/BC_PUB/RNA/RNA_RNAdenovo/RNA_RNAdenovo_2018a/software/Trinity line 853.
2019-09-10 03:52:47 ERROR: The assembler failed with error: Command 'Trinity --seqType fa --max_memory 13G --CPU 6 --output '/tmp/atram_xpc10ieb/Acheilognathidae_Acheilognathus_tonkinensis_ST_Acheilognathidae_Acheilognathus_tonkinensis_ST.E0027.fq.initial.combined.fa_01_x90wmut1/trinity' --full_cleanup --no_bowtie' returned non-zero exit status 255


**My mix-ends fq:**
@SRR4578725.2090912/1
CTACTGCAGGAAAAGGTTAATTACTGCTCTGGGGTCATTCAAAGAGTGATTAACATCTATTTACATTCAATTCGAAAGGGTATTTTTCATTATCTGACCTCTAGGTCATCCTGCTGCTCCTGTAGCCCCTCCAGACCACTGAGATCAGAG
+
CCCFFFFFHHHHHJJJGHJJJJJJJJJJJJJJJJFHIJJJJJJJJJGHHIJIJJJJJJIJJJJJJJJJIJJJJJIJHHHF?CEFFEAEEEFEEDDEDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCD
@SRR4578725.2090912/2
TGTGCAGAGCTCAGCATGGACCTCCTGGACGTAGAAACAGATATGGCTGTGTTTTGTGACTCTGATCTCAGTGGTCTGGAGGGGCTACAGGAGCAGCAGGATGACCTAGAGGTCAGATAATGAAAAATACCCTTTCGAATTGAATGTAAA
+
CCCFFFFFHHHHHGHIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJGHHIJJHGIIJJIJJGIIIHFHCHHBDFFFDEDDDDBDDDDDBBBDDDDDD@CA@CDDDDDDD>CDDDDDDDDCCDDDDD@CDCDDDDBDDDCCDDDCDEE
@SRR4578725.50157/1
CTAGGGTTTATATGGCGACTAGAGAGAGCCGTGCTACGAGAAGAGAGGGCCGTTCTGTGATCAGGCCGTCCTGTTTGGCTTGAAGAGACCAAAGTCACAGTGTCTATGAGGAGGAAGAGAATTCACATTGCTGTCCGCTAGCGGGACACG
+
CCCFFFDDHHHHHJJIJJJJJJJJJJIJJJJIIJIJJJGHEGIGIJJJJHHFFDEDEDDEEEEDDCDDDDDDDDDDDDD@A>?CCCDDDDDDDDCDEDDDD>ADDEEEDDDDDD?BDDDDCCCCDDDDDCDDDDDDDDDDDDDDDDDDDD
@SRR4578725.50157/2
GTCCATCCTTAAATCGTTATAACAATCTTTAATTGTTTGAATTGTTTCATGTCTCTAGCCTCCTGGTCGTGAGAAGCGACGTGTCCCGCTAGCGGACAGCAATGTGAATTCTCTTCCTCCTCATAGACACTGTGACTTTGGTCTCTTCAA
+
CCCFFFFFHHHHHJJJJJJJJJJJJJJJJJJIJJJJJJIJJJJJJJJJJJJJJJJJJGIJJJJJIJHIGIIIJJHHHFFFDDDDDDDDDDDDDDDDDDDDDCDDDEEEEEDEDDDDDDDDDDDDDDDDDDDDDDEDDDDDDDDDDDDDEC

**Comment by rafelafrance** [comment]
Sorry for the inconvenience. I'll get to this asap.

**Comment by rafelafrance** [comment]
Your data and parameters to both programs look fine. Just to be sure I ran a test by replacing my normal --end-1 and --end-2 files as both --mixed-ends. The database was built by the preprocessor correctly and atram (trinity) worked too.

It is possible that the last "git pull" you did not get the latest version of atram. We can test this by doing:

```
git log --oneline -1
```

Could you report what you get when you run that from the atram directory? I expect to see something like:
```
bcd4867 (HEAD -> master, origin/master, origin/HEAD) Handle uneven version lengths in check utility
```

**Comment by yuhuang-genomics** [comment]
git log --oneline -1

This's what I get:
875acae Fix tests related to new DB structure

**Comment by rafelafrance** [comment]
That is several versions back and you're missing one important commit related to this issue. Would you please do the following again.
```
cd my/atram/directory
git pull
./atram_prepressor.py ... The same arguments from before
./atram.py ... The same arguments
```

**Comment by yuhuang-genomics** [comment]
Thanks Rafe. That's the problem. After git pull, I ran another test with mixed-ends and it works. The db version changed from atram v2.2 to atram v2.3.

**Comment by rafelafrance** [comment]
Excellent.

Just so you're aware, you are running a bleeding-edge version of aTRAM and this is not the official version of aTRAM v2.3 just yet.
