### ISSUE TITLE
Understanding spades errors

### ISSUE THREAD

**Issue by HeatherKates** [juliema/aTRAM#266]
Hi Julie and Rafe,
I've gotten spades error "the assembler failed with the error...returned non-zero exist status 1" many times in the past using atram. We have high overall assembly rates so I haven't give this much thought yet, but I'd like to understand it as I go through data QC for the project.

The spades logs are verbose (like, literally I mean) and it's a lot to wade through. It happens when there are very few blast hits, and it happens in iteration 1 or 2 (I think). I guess I'd expect it to print "No [new] contigs were found" instead of an error that quits spades (it moves to the next locus in -Q reference.fasta). I attached a *log that atram outputs as well as what's printed to stdout. The stdout is truncated bc it was too big to attach, but it has examples. I also attached a short *log for a single locus run in case it's easier to start there.
[P055_WH12.Locus.log](https://github.com/juliema/aTRAM/files/3632975/P055_WH12.Locus.log)
[55atram.40888404.txt](https://github.com/juliema/aTRAM/files/3632964/55atram.40888404.txt)
[WA02.log](https://github.com/juliema/aTRAM/files/3632940/WA02.log)

Thanks for looking at this!
Heather Rose

**Comment by rafelafrance** [comment]
Some assemblers are quite chatty.  On the plus side, the errors are almost always in the last few lines of the log files. I open up my editor and go to the end of the file and work upwards.

Here spades is complaining about poor coverage. I don't know enough about assemblers in general or spades in particular to give you any advice on what this actually means:

```
Verification of expression 'cov_.size() > 10' failed
<<snip>>
Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
```

**Comment by juliema** [comment]
yeah usually when assemblers fail it is because they don't have enough reads to assemble anything and somewhere in the assembly process it fails.  I suspect that is what is going on here but all assemblers behave a little differently.

On Fri, Sep 20, 2019 at 10:11 AM rafe <notifications@github.com<mailto:notifications@github.com>> wrote:

Assigned #266<https://github.com/juliema/aTRAM/issues/266> to @juliema<https://github.com/juliema>.
