### ISSUE TITLE
atram_framer.py change sequence header format

### ISSUE THREAD

**Issue by HeatherKates** [juliema/aTRAM#268]
Hi Rafe,
The sequence headers in the Yang and Smith pipeline are TaxonID@ClusterID.
Currently, the sequence headers printed by framer are:
>Medtr5g099060_1@P023_WH12_1_NODE_1_length_2427_cov_21_283830__iteration_1_contig_id_NODE_1_length_2427_cov_21_283830_score_426_787_1
The critical change that is needed is that this should be
>P023_WH12@Medtr5g099060 #P023_WH12 is the TaxonID, Metr5g... is the ClusterID.
We should save contig ids minimally. Maybe
>P023_WH12@Medtr5g099060_i1c21s426 #save iteration no., cov., and score abbreviate to one letter and truncate or round the float (if the header can't have ".", then to the integer). I left the length out because that is obvious from the sequence.

**Comment by rafelafrance** [comment]
I think i fixed this in a previous commit. Please `git pull` and try again.

**Comment by rafelafrance** [comment]
Current patch:

- The file writer back to one file per reference gene
- The framer contig ID is `<taxon id>@<ref name>_<header up to first space>_<tie breaker>`
- Any odd characters with an underscore "_"

**Comment by HeatherKates** [comment]
Rafe, you're right I was a version behind. I'd still like the contig IDs shorter/less info. removed. What's tie breaker? Here's what I'd prefer ultimately (though this is definitely usable as is)
>P023_WB03@Medtr1g056530_1_1_NODE_10_length_234_cov_0_929936__1589
>P023_WB03@Medtr1g056530_**i**1_~1_NODE_10~_**l**~ength~_234_**c**~ov_0_929936~**1**~__1589~**score?**
i.e.
>P023_WB03@Medtr1g056530_i1C1SX
Only iteration, coverage, and score should be printed in the contig ID. The other information is not needed, and the overly long names will just be a pain in post-processing.

**Comment by rafelafrance** [comment]
Please send me your input files so that I can actually debug this.

**Comment by HeatherKates** [comment]
Sure thing. Here they are: https://drive.google.com/drive/folders/1eiBFD_iqCE1xH3Q-MdN-E4hYad34PxsE?usp=sharing

Ran with `python aTRAM/atram_framer.py -a Assemblies/ -r Reference.fasta -o NewVersion -T Taxon_list.txt`

version is atram_framer.py v2.3.0

**Comment by rafelafrance** [comment]
So the names are looking like:

`>P023_WB05@Medtr2g022140_1_1_NODE_8_2032`
`>P023_WA11@Medtr1g072540_1_3_NODE_1_961`

Is this OK?

FYI: A tiebreaker is something that guarantees that the name is unique across the run. In this case, it's just a record count. I.e. it's something so that if you need to grep an ID across all of the files you know you'll only ever get one hit.

**Comment by HeatherKates** [comment]
Thanks Rafe- not quite. Other than node (which we don't need to print), I'm not sure what those other numbers are, I think some are right and others are not. The numbers should probably have at least the first letter of what they're recording before them. It may be clearer to refer to the original headers (in my previous post I started with framers current output):
Here's the original header from spades/atram, with the values we want to save in bold. It's a bit confusing because the headers are repetitive. I think 1 before NODE is also iteration, and obviously coverage and length are both printed twice because atram adds some text to the header.
>1_NODE_4_length_697_**cov_28**.996774_ **iteration=1** contig_id=NODE_4_length_697_cov_28.996774 **score=173**.326

**Comment by rafelafrance** [comment]
`P023_WB01@Medtr1g056530_1_i1c0s73`
`>P023_WA03@Medtr1g062710_1_i1c11s127`

**Comment by HeatherKates** [comment]
Yeah!! Is it possible to round coverage rather than truncate? As you can see, 0.929... (which is multiplied by 2 to get nuc cov of 2x) becomes 0 which is just 0. It probably doesn't really matter, if a contig has such low kmer cov that truncating makes a big difference, that contig should probably be filtered out (see my other issue on the coverage filter)

**Comment by rafelafrance** [comment]
Values for the coverage and score are now rounded

**Comment by rafelafrance** [comment]
I'm glad I asked you for a real input file because with all of this rounding etc. there turns out to be duplicate sequence names in the framer fasta output.

So, there still needs to be a tiebreaker in the sequence names. I'll keep it short by adding a small value like '_a" or '_b' to the end of sequences but only in the case where there are duplicates.

Unless you're sure that duplicate names should never occur then I'll start the bug hunt.
