### ISSUE TITLE
atram_preprocessor.py error with multiple fastq files

### ISSUE THREAD

**Issue by MareikeJaniak** [juliema/aTRAM#272]
Hi! 
I just updated to the latest version of aTRAM and I tried to build fresh libraries, but I am getting an error when trying to run atram_preprocessor.py that I was not getting before. 

When trying to use multiple fastq files as input, either by entering multiple file names after --end-1/--end-2 or by using a wildcard, atram immediately throws the following error:

usage: atram_preprocessor.py [-h] [--version] [--end-1 FASTA/Q]
                             [--end-2 FASTA/Q] [--mixed-ends FASTA/Q]
                             [--single-ends FASTA/Q] [-b DB] [--cpus CPUS]
                             [-t DIR] [--keep-temp-dir] [-l LOG_FILE]
                             [-s SHARDS] [--path PATH] [--fasta] [--fastq]
                             [--gzip] [--bzip]
atram_preprocessor.py: error: unrecognized arguments: /home/mcj43/scratch/Foraging_paper/TR_genes/fastq/Alouatta/HGV2KDSXX_2_143UDI-idt-UMI-header_1.fastq.gz /home/mcj43/scratch/Foraging_paper/TR_genes/fastq/Alouatta/HGV2KDSXX_2_143UDI-idt-UMI-header_2.fastq.gz

The files in the "unrecognized arguments" correspond to the second fastq input files. My full command is here:

/home/mcj43/software/aTRAM/atram_preprocessor.py -b /home/mcj43/scratch/Foraging_paper/TR_genes/aTRAM/libraries/Alouatta --end-1 /home/mcj43/scratch/Foraging_paper/TR_genes/fastq/Alouatta/HGV2KDSXX_1_143UDI-idt-UMI-header_1.fastq.gz /home/mcj43/scratch/Foraging_paper/TR_genes/fastq/Alouatta/HGV2KDSXX_2_143UDI-idt-UMI-header_1.fastq.gz --end-2 /home/mcj43/scratch/Foraging_paper/TR_genes/fastq/Alouatta/HGV2KDSXX_1_143UDI-idt-UMI-header_2.fastq.gz /home/mcj43/scratch/Foraging_paper/TR_genes/fastq/Alouatta/HGV2KDSXX_2_143UDI-idt-UMI-header_2.fastq.gz --fastq --gzip

Using wildcards instead of entering two files throws the same error.

**Comment by rafelafrance** [comment]
The one thing you didn't try is repeating the arguments like:
`--end-1 file1a.fq --end-1 file1b.fq`

This is admittedly confusing. We should either update the help or allow the other forms you tried.

**Comment by MareikeJaniak** [comment]
Ok, I will try that! Sorry, I miss understood how to enter multiple files. 

Was this different in previous versions of aTRAM? I have old scripts in which I (seemingly) used wildcards successfully. 

Thanks for your quick response!

**Comment by rafelafrance** [comment]
It did change, _mea culpa_.

We're going to accept all 3 forms in the future.

**Comment by MareikeJaniak** [comment]
No worries! And thanks so much for changing it in future versions!

**Comment by rafelafrance** [comment]
Is covered by issue #273
