### ISSUE TITLE
Add more parameter options for abyss-pe

### ISSUE THREAD

**Issue by adsweet** [juliema/aTRAM#279]
It would be nice for a user to have control over the parameter settings in abyss-pe, including the "p" option for minimum sequence identity.

**Comment by rafelafrance** [comment]
Aside from the -p option, which ones would be most useful to your work?

**Comment by adsweet** [comment]
Sorry for the late reply…this went to my junk mail for some reason.

I think the -p option would be nice to try first. Julie and I are trying to figure out a way for aTRAM to assemble different alleles, which I think would require the user to change the consensus stringency in assembly software (i.e, can we force reads with 100% identity to assemble into contigs, vs. reads with e.g. 90% identity?). Based on the Abyss manual, I think the -p option is our best bet to get what we want, but I’m not sure.

Thanks,

Drew

**Comment by rafelafrance** [comment]
Because "p" is not a unique name for an argument, I called it "--abyss-p".

**Comment by adsweet** [comment]
Ok thanks.
