### ISSUE TITLE
aTRAM/2.3.0 spades and python2 compatibility issues

### ISSUE THREAD

**Issue by HeatherKates** [juliema/aTRAM#286]
Hi Rafe and Julie,

I brought this issue up a while back (maybe via email) but then abandoned it. Would like to figure it out. I've never had success assembling with the current version of atram (v 2.3.0) on hipergator, I believe due to a spades/python incompatibility error. With the same input files and run command, atram v 2.1.0 runs fine, but atram 2.3.0 throws a spades error. The current install on hipergator loads:
SPAdes version: 3.12.0
Python version: 2.7.12

The atram documentation lists python3 and spades 3.11.1 as requirements. Python2 automatically loads when any version of spades is loaded on hipergator, including in the version 3.11 listed as required in the atram documentation. I can work with hipergator staff to get the compatible software loaded as part of module load atram, but I know it's tricky for them to change what python co-loads with what software, so I just want to double check what is and is not relevant before I start that. Do you expect specific spades version really matters? Why did python2 work with atram v. 2.1.0 but not 2.3.0? I guess both those questions get at - is spades or python incompatibility the issue, or both. Thanks!

Here's a link to example input data and a log file with output from the successful runs (v 2.1.0) and failed runs (v 2.3.0) https://drive.google.com/open?id=1Yq-GyOqOzxFeZkPwvK9uhSH-l6h5aIF6

**Comment by rafelafrance** [comment]
Atram needs Python 3.6 or greater. Preferably, Python 3.7+.  If Python2.7 worked on atram 2.1 I have no idea why. It really shouldn't have.

Try to get the matching version but there is typically some version wiggle room with the assemblers and blast.
