### ISSUE TITLE
--timeout 0 exits immediately

### ISSUE THREAD

**Issue by sestaton** [juliema/aTRAM#288]
I was getting an issue of `tblastn` timing out so I tried to adjust the `--timeout` option. The help menu suggests that if you set this to zero (`-T 0`) it will wait forever. However, this makes the processes exit immediately.

This seems to be a bug because if I run the blast processes that exited they run fine, and if I set `-T` to an arbitrarily large number the program also runs fine. So, it would appear that the program is setting `-T 0` to literally zero instead of forever.

**Comment by rafelafrance** [comment]
Bug fixed. Thanks for the report.

**Comment by sestaton** [comment]
Great, thanks!
