### ISSUE TITLE
add --np flag to abyss to tell it how many cpus to use 

### ISSUE THREAD

**Issue by juliema** [juliema/aTRAM#296]
add --np  to the abyss commands

**Comment by rafelafrance** [comment]
Abyss already uses the np= option. It is tied to the --mpi and --cpus arguments. Quoting from the help:

``
--mpi  Use MPI for this assembler. The assembler must have been compiled to use MPI.
          Abyss: If this is true then pass --cpus <int> into np=<int>.
``

**Comment by rafelafrance** [comment]
I suppose I can change the arguments to be clearer.

**Comment by rafelafrance** [comment]
All assembler switches are now explicit. That is they are now in the form:

```
--trinity-option value
--abyss-switch
```
Trying to combine them was causing confusion.
