### ISSUE TITLE
atram_preprocessor TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by n-oury** [juliema/aTRAM#299]
Hi,

I am trying to run atram_preprocessor with the latest version of aTRAM but encountered an issue.
I have two gzipped fastq files (R1 & R2) resulting from cutadapt (~2,600,000 reads each).
Below is my command line:
python atram_preprocessor.py --blast-db=MAD3_066 --end-1=MAD3_066-1_S171_L001_R1_001_val_1.fq.gz --end-2=MAD3_066-1_S171_L001_R2_001_val_2.fq.gz --fastq --gzip

And the resulting output:
2020-11-30 15:52:56 INFO : ################################################################################
2020-11-30 15:52:56 INFO : aTRAM version: v2.3.4
2020-11-30 15:52:56 INFO : Python version: 3.8.5 (default, Sep 4 2020, 07:30:14) [GCC 7.3.0]
2020-11-30 15:52:56 INFO : atram_preprocessor.py --blast-db=MAD3_066 --end-1=MAD3_066-1_S171_L001_R1_001_val_1.fq.gz --end-2=MAD3_066-1_S171_L001_R2_001_val_2.fq.gz --fastq --gzip
2020-11-30 15:52:56 INFO : Creating an index for the sequence table
2020-11-30 15:52:56 INFO : Assigning sequences to shards
Traceback (most recent call last):
File "atram_preprocessor.py", line 179, in <module>
preprocess(ARGS)
File "/home/noury/aTRAM/lib/core_preprocessor.py", line 40, in preprocess
shard_list = assign_seqs_to_shards(
File "/home/noury/aTRAM/lib/core_preprocessor.py", line 95, in assign_seqs_to_shards
cuts = [db_preprocessor.get_shard_cut(cxn, offset) for offset in offsets]
File "/home/noury/aTRAM/lib/core_preprocessor.py", line 95, in <listcomp>
cuts = [db_preprocessor.get_shard_cut(cxn, offset) for offset in offsets]
File "/home/noury/aTRAM/lib/db_preprocessor.py", line 91, in get_shard_cut
cut = result.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

I saw the same Traceback in a previous threads #284 but this was resolved by adding the --fastq argument.
I have deduced the issue probably come from input files so I tried to rename the input extensions (*.fastq.gz), with unzipped fastq, and with toys fastas (500 sequences; not zipped), but it changed nothing.
Also, I ran the util_check_requirements.py script and everything is correctly installed (I tried with aTRAM and dependencies installed manually and with miniconda, it changed nothing).

Perhaps the issue comes from the fastq formatting, so below are the first lines of the input files (I have truncated the lines):
 
MAD3_066-1_S171_L001_R1_001_val_1.fq.gz:
@A00786:83:HH5H2DRXX:1:2101:3423:1000 1:N:0:TCCGCGAA+CCTATCCT
GGGAAATTTC...
+
FFFFFFFFFF...
@A00786:83:HH5H2DRXX:1:2101:9516:1000 1:N:0:TCCGCGAA+CCTATCCT
CTCAATGTAA...
+
FFFFFFFFFF...

MAD3_066-1_S171_L001_R2_001_val_2.fq.gz:
@A00786:83:HH5H2DRXX:1:2101:3423:1000 2:N:0:TCCGCGAA+CCTATCCT
TAACCTGTGA...
+
FFFFFFFFFF...
@A00786:83:HH5H2DRXX:1:2101:9516:1000 2:N:0:TCCGCGAA+CCTATCCT
TGGAAGACGA...
+
FFFFFFFFFF...

Any idea?

Best regards,

Nicolas

**Comment by juliema** [comment]
Hey Nicolas,

Will you first check the validity of the gzipped files by running the
following in the shell?

gzip -vt my_file.fq.gz

**Comment by juliema** [comment]
replace 'my_file'  with your filename.

**Comment by n-oury** [comment]
Hi Julie,

Both files are OK.

Best,

Nicolas

**Comment by juliema** [comment]
Ok would you mind trying without the files gzipped and remove the --gzip
option?

**Comment by n-oury** [comment]
The problem did not come from the input files.
I just rerun the command with the same files but this time in the aTRAM folder and it works.

Thanks for your help,

Nicolas

**Comment by RominaSSBatista** [comment]
Hi, thank you so much for this repository and all documentation related to aTRAM. It is very helpful. 

I am trying to run aTRAM preprocessor (HPC) and the output I am getting is as following: 

```
(   15569) 2022-12-12 16:38:45.740412 INFO : ################################################################################
(   15569) 2022-12-12 16:38:45.741501 INFO : aTRAM version: v2.4.4
(   15569) 2022-12-12 16:38:45.741802 INFO : Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) [GCC 9.4.0]
(   15569) 2022-12-12 16:38:45.742158 INFO : $aTRAM_PATH/atram_preprocessor.py -b $aTRAM_output/libraries/PD_1342 --cpus 10 -l $aTRAM_output/logs/PD_1342.preprocess.log -t /work/scratch-nopw/rominab/ --end-1 $DATA_PATH/PD_1342-READ1.1500000.fastq.gz --end-2 $DATA_PATH/PD_1342-READ2.1500000.fastq.gz --fastq --gzip
(   15569) 2022-12-12 16:38:46.087312 INFO : Creating an index for the sequence table
(   15569) 2022-12-12 16:38:46.113663 INFO : Assigning sequences to shards
Traceback (most recent call last):
  File "$aTRAM_PATH/atram_preprocessor.py", line 179, in <module>
    preprocess(ARGS)
  File "$aTRAM_PATH/aTRAM/lib/core_preprocessor.py", line 40, in preprocess
    shard_list = assign_seqs_to_shards(
  File "$aTRAM_PATH/aTRAM/lib/core_preprocessor.py", line 95, in assign_seqs_to_shards
    cuts = [db_preprocessor.get_shard_cut(cxn, offset) for offset in offsets]
  File "$aTRAM_PATH/aTRAM/lib/core_preprocessor.py", line 95, in <listcomp>
    cuts = [db_preprocessor.get_shard_cut(cxn, offset) for offset in offsets]
  File "$aTRAM_PATH/aTRAM/lib/db_preprocessor.py", line 91, in get_shard_cut
    cut = result.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
```

If I run: 

```
[rominab@sci2 aTRAM]$ ./util_check_requirements.py 
Python version.......................... OK
makeblastdb............................. OK
tblastn................................. OK
blastn.................................. OK
abyss................................... OK
trinity................................. OK
velvet.................................. OK
spades.................................. OK
bwa..................................... OK
bowtie2................................. OK
exonerate............................... OK
Traceback (most recent call last):
  File "./util_check_requirements.py", line 126, in <module>
    check_modules()
  File "./util_check_requirements.py", line 39, in check_modules
    installed_modules = parse_requirements(modules.decode('utf-8'))
  File "./util_check_requirements.py", line 29, in parse_requirements
    module = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Any advice is going to be appreciated. 
Thank you,
Romina
